### ISSUE TITLE
Link in ReadMe to Demo INOP

### ISSUE THREAD

**Issue by KKenui** [mehmetgoren/feniks#1]
The link to the live demo does not load when clicked. 

http://46.197.220.143/

The connection has timed out

The server at 46.197.220.143 is taking too long to respond.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

**Comment by mehmetgoren** [comment]
Thank you for reporting the issue, the link is available now.
