### ISSUE TITLE
Warning message about motion detection

### ISSUE THREAD

**Issue by guillemmateos** [mehmetgoren/feniks#15]
When running the docker-compose set on a source I enabled (a Ubiquiti camera) I can see this line multiple times in the logs:

motion detection filter is not ok for source(source-id)

Coming from the snapshot_service container.

I've checked the code and I'm unsure why this message is generated and how to fix it. Is it expected to see this message for sources? Do I have to enable a specific config for sources?

I've also built Google Coral TPU support for feniks so I will hopefully be submitting a PR soon for the relevant repos to enable that.

**Comment by mehmetgoren** [comment]
The messages in question can be safely removed as they do not hold any significant or meaningful content.
