### ISSUE TITLE
open database file: out of memory error

### ISSUE THREAD

**Issue by gjtjx** [mehmetgoren/feniks#16]
2023/07/22 21:29:50 /app/data/sqlt/db_context.go:20
smcp-instance       | [error] failed to initialize database, got error unable to open database file: out of memory (14)

smcp-instance 、mngr-instance exited with code 2

any help?
[log.txt](https://github.com/mehmetgoren/feniks/files/12136585/log.txt)

[docker-compose.txt](https://github.com/mehmetgoren/feniks/files/12136587/docker-compose.txt)

**Comment by mehmetgoren** [comment]
First of all, do you use SQLite or MongoDB for your AI event database? If you use SQLite, I strongly recommend that you switch to MongoDB for now. The SQLite version is not mature enough at the moment.

**Comment by gjtjx** [comment]
How to change the docker compose configure to MongoDB? I have set No in wizard: Add Redis and MongoDB entries to Docker-Compose YAML file and install MongoDB by Docker

**Comment by mehmetgoren** [comment]
Database cannot be selected from the Docker Compose YAML file, but you can change it from the "Config > Database" section as shown below:
![config](https://github.com/mehmetgoren/feniks/assets/9039657/37e20f4a-2fa5-4fe2-961c-3cc1b10af37b)

All Docker containers will be restarted after clicking the save button.

**Comment by gjtjx** [comment]
I can't login in , becuse smcp-instance 、mngr-instance exited with code 2

**Comment by mehmetgoren** [comment]
It seems that your config file is not correct. Could you please set the configuration (which is attached to this message) file to your Redis instance as shown below? To do that, you can use Redis GUI software like "GUI for Redis".
![Screenshot from 2023-07-24 12-42-45](https://github.com/mehmetgoren/feniks/assets/9039657/df1c4c42-487a-46c6-aea7-4d621a2c72dc)


[redis_config.txt](https://github.com/mehmetgoren/feniks/files/12144271/redis_config.txt)

**Comment by gjtjx** [comment]
This config have  solve my problem,Thank you very much!
